TRUNCATE TABLE CITY;
INSERT INTO CITY (ID,COUNTRY_CODE, NAME) VALUES(1,'JPN', 'TOKYO');
INSERT INTO CITY (ID,COUNTRY_CODE, NAME) VALUES(2,'USA', 'NEW YORK');
INSERT INTO CITY (ID,COUNTRY_CODE, NAME) VALUES(3,'GBR', 'LONDON');